services:
  app:
    image: tassioauad/infnet-guia-app
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - target: 3000
        published: 80
        mode: ingress
    networks:
      - infnet-network
  database:
    image: mysql:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: infnet-studies-mngmt-db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    expose:
      - 3306
    volumes:
      - /mnt/data/mysql_data:/var/lib/mysql
    networks:
      - infnet-network
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global
      restart_policy:
          condition: on-failure
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - infnet-network
  prometheus:
    image: prom/prometheus
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /mnt/data/prometheus_data:/prometheus
    networks:
      - infnet-network
networks:
  infnet-network:
    driver: overlay