global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  static_configs:
  - targets:
    - prometheus:9090
- job_name: cadvisor
  static_configs:
  - targets:
    - ip-172-31-94-58.ec2.internal:8080 #node1 manager
    - ip-172-31-90-76.ec2.internal:8080 #node2 worker
    - ip-172-31-88-64.ec2.internal:8080 #node3 worker
    - ip-172-31-88-253.ec2.internal:8080 #node4 worker
