name: Docker Image CI

on:
  push:
    branches: [ "releases/**" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:  
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Docker tag dynamically
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
        else
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
          echo "DOCKER_TAG=$BRANCH_NAME" >> $GITHUB_ENV
        fi

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$DOCKER_TAG .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$DOCKER_TAG
